name: Apptainer Build Deploy

on:
  # Configures this workflow to run every time a new release is created.
  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write

    container:
      image: ghcr.io/apptainer/apptainer:latest
      options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Container
        run: apptainer build fithichip.sif singularity.def

      - name: Log in to the Container registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u ${{ github.actor }} --password-stdin oras://ghcr.io
           
      - name: Push apptainer
        run: apptainer push fithichip.sif oras://ghcr.io/${{ github.repository_owner }}/fithichip:${{ github.ref_name }}
